#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend kadahdigitalworld.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 149959-web-01 100.25.201.131:80
        server 149959-web-02 18.208.120.48:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
